import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Vehicle from './models/Vehicle.js';
import connectDB from './config/db.js';

dotenv.config();

const sampleVehicles = [
  {
    brand: 'BMW',
    model: '3 Series 330i M Sport',
    year: 2023,
    price: 4850000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 14200,
    location: 'Mumbai, Maharashtra',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    description: 'Immaculately maintained BMW 330i M Sport with complete service history at authorized BMW service center. Features Dravit Grey metallic paint, Vernasca Cognac leather seats, Harmon Kardon surround sound system, and M aerodynamic package.',
    engine: '2.0L TwinPower Turbo Inline-4 (255 HP)',
    category: 'Sedan',
    isFeatured: true,
    features: [
      'Wireless Apple CarPlay & Android Auto',
      'Panoramic Glass Sunroof',
      '360 Parking Camera with Park Assist',
      'Harmon Kardon 16-Speaker Audio',
      'Adaptive LED Headlamps',
      'Ambient Lighting with 11 Colors',
    ],
  },
  {
    brand: 'Mercedes-Benz',
    model: 'C-Class C220d Progressive',
    year: 2022,
    price: 5200000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    mileage: 21500,
    location: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    description: 'Executive-driven Mercedes-Benz C220d in pristine Obsidian Black. Offers industry-leading cabin quietness, 9G-TRONIC smooth transmission, and legendary German craftsmanship with high fuel efficiency.',
    engine: '2.0L OM654 Turbocharged Diesel (200 HP)',
    category: 'Luxury',
    isFeatured: true,
    features: [
      '11.9-inch Portrait MBUX Display',
      'Burmester 3D Surround Sound',
      'Active Brake Assist & Blind Spot Assist',
      'Ventilated Front Seats with Memory',
      'Air Balance Cabin Fragrance Package',
    ],
  },
  {
    brand: 'Audi',
    model: 'A4 40 TFSI Technology',
    year: 2023,
    price: 4400000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 11000,
    location: 'Bengaluru, Karnataka',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
    description: 'Single-owner Audi A4 Technology pack featuring Audi Virtual Cockpit Plus, Matrix LED headlights, and 12-way power seats. Smooth 7-speed S-Tronic dual-clutch transmission with rapid gear changes.',
    engine: '2.0L 40 TFSI Turbo Petrol (204 HP)',
    category: 'Sedan',
    isFeatured: true,
    features: [
      'Audi Virtual Cockpit Plus (12.3 inch)',
      'Matrix LED Headlights with Dynamic Indicators',
      'Bang & Olufsen 3D Sound System',
      'Wireless Phone Charging Pad',
      '3-Zone Deluxe Climate Control',
    ],
  },
  {
    brand: 'Toyota',
    model: 'Fortuner 4x4 Legender',
    year: 2023,
    price: 4350000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    mileage: 26000,
    location: 'Pune, Maharashtra',
    image: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=1200&q=80',
    description: 'Tough, reliable, and commanding road presence. Toyota Fortuner Legender equipped with rugged 4WD system, premium maroon-black perforated interior, and unmatched Toyota resale dependability.',
    engine: '2.8L D-4D Turbo Diesel (204 HP / 500 Nm)',
    category: 'SUV',
    isFeatured: true,
    features: [
      'Active Traction Control 4x4',
      'Hands-Free Power Back Door with Kick Sensor',
      '11-Speaker JBL Audio System',
      'Ventilated Cooled Front Seats',
      'Differential Lock with Terrain Modes',
    ],
  },
  {
    brand: 'Hyundai',
    model: 'Creta SX (O) Turbo DCT',
    year: 2024,
    price: 1875000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 8500,
    location: 'Hyderabad, Telangana',
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80',
    description: 'Latest generation Hyundai Creta top trim with Level 2 ADAS suite, dual 10.25-inch connected screens, panoramic sunroof, and Bose 8-speaker premium audio system. Like-new showroom condition.',
    engine: '1.5L Turbo GDi Petrol (160 HP)',
    category: 'SUV',
    isFeatured: false,
    features: [
      'Hyundai SmartSense Level 2 ADAS',
      'Dual Integrated 10.25-inch Screens',
      'Panoramic Sunroof (Voice Enabled)',
      'Bose 8-Speaker Audio System',
      'Front Ventilated Seats',
    ],
  },
  {
    brand: 'Tata',
    model: 'Harrier Fearless Plus Dark Edition',
    year: 2024,
    price: 2450000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    mileage: 7200,
    location: 'Chandigarh',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    description: 'Built on the Land Rover-derived OMEGArc platform, the Tata Harrier Dark Edition combines 5-star GNCAP safety with stealth black aesthetics, electronic power steering, and paddle shifters.',
    engine: '2.0L Kryotec Turbo Diesel (170 HP)',
    category: 'SUV',
    isFeatured: true,
    features: [
      '5-Star Global NCAP Safety Rating',
      '12.3-inch Ultra-HD Touchscreen',
      'Level 2 ADAS with 11 Safety Functions',
      'JBL 10-Speaker Audio with Subwoofer',
      '360 Surround Camera with Blind View Monitor',
    ],
  },
  {
    brand: 'Kia',
    model: 'Seltos X-Line 1.5 Turbo',
    year: 2023,
    price: 1980000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 15400,
    location: 'Ahmedabad, Gujarat',
    image: 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=1200&q=80',
    description: 'Stunning Matte Graphite finish Kia Seltos X-Line. Features sage green leatherette interior, heads-up display, dual-pane panoramic sunroof, and responsive 7-speed dual-clutch transmission.',
    engine: '1.5L Smartstream T-GDi (160 HP)',
    category: 'SUV',
    isFeatured: false,
    features: [
      '8-inch Smart Heads-Up Display (HUD)',
      'Dual Zone Fully Automatic Temperature Control',
      'Level 2 ADAS Autonomous Tech',
      'Electric 8-Way Driver Seat',
      'All-Wheel Disc Brakes',
    ],
  },
  {
    brand: 'Honda',
    model: 'City e:HEV Strong Hybrid ZX',
    year: 2023,
    price: 1890000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    mileage: 19000,
    location: 'Chennai, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    description: 'Honda City e:HEV self-charging dual-motor hybrid delivering an incredible 27+ kmpl real-world mileage. Supreme ride comfort, Honda Sensing ADAS, and whisper-quiet pure EV driving mode.',
    engine: '1.5L Atkinson Cycle i-VTEC + Dual Electric Motors (126 HP)',
    category: 'Sedan',
    isFeatured: false,
    features: [
      'Self-Charging e:HEV Dual Motor Hybrid',
      'Honda SENSING Advanced Driver Assist',
      'Electric Parking Brake with Auto Hold',
      'Lanewatch Camera',
      '27.13 km/l ARAI Fuel Efficiency',
    ],
  },
  {
    brand: 'Tata',
    model: 'Nexon EV Empowered Plus LR',
    year: 2024,
    price: 1820000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    mileage: 6400,
    location: 'Bengaluru, Karnataka',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80',
    description: 'India\'s best-selling electric SUV with long-range 40.5 kWh battery pack (465 km certified range). Supports fast DC charging, Vehicle-to-Load (V2L) power output, and zero tailpipe emissions.',
    engine: 'Permanent Magnet Synchronous Motor (145 HP / 215 Nm)',
    category: 'Electric',
    isFeatured: true,
    features: [
      '40.5 kWh High-Density LFP Battery',
      'Vehicle-to-Vehicle (V2V) & V2L Power Bank',
      '12.3-inch Cinematic Touchscreen by HARMAN',
      'Blind Spot View Monitor',
      'Electronic Parking Brake with Auto Hold',
    ],
  },
  {
    brand: 'Porsche',
    model: 'Macan GTS V6 Twin-Turbo',
    year: 2022,
    price: 9200000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 18500,
    location: 'Mumbai, Maharashtra',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    description: 'The sports car of compact SUVs. Carmine Red Porsche Macan GTS featuring sport air suspension, Porsche Active Suspension Management (PASM), sports exhaust system, and 0-100 km/h in 4.3 seconds.',
    engine: '2.9L Twin-Turbocharged V6 (434 HP)',
    category: 'Luxury',
    isFeatured: true,
    features: [
      'Sport Chrono Package with Mode Switch',
      'Porsche Ceramic Composite Brakes (PCCB)',
      'Adaptive 18-Way Sports Seats Plus',
      'BOSE Surround Sound System',
      'Sport Exhaust with Black Tailpipes',
    ],
  },
];

const seedData = async () => {
  try {
    await connectDB();

    console.log(' Clearing existing vehicle listings...');
    await Vehicle.deleteMany();

    console.log(' Inserting 10 premium sample vehicles...');
    const createdVehicles = await Vehicle.insertMany(sampleVehicles);

    console.log(` Successfully seeded ${createdVehicles.length} vehicles into MongoDB!`);
    process.exit(0);
  } catch (error) {
    console.error(' Seeding failed:', error);
    process.exit(1);
  }
};

seedData();
